Repository BC-MAY-21-RN/kata-05-reservacion-de-vuelos-m22-k05-t4-reactive-04, pull requests merged in 2022-06, with the labels that each got.

#7 Register Form - Feature# design
  App.js
  android/app/build.gradle
  android/build.gradle
  android/google-services.json
  package-lock.json
  package.json
  src/assets/img/Registro.studio
  src/assets/img/booking.png
  src/assets/img/booking.studio
  src/assets/img/cover.jpg
  src/assets/img/logo-bc.png
  src/assets/img/my-flights.png
  src/assets/img/my-flights.studio
  src/assets/img/registro.png
  src/components/atoms/CustomButton/CustomButtonStyles.js
  src/components/atoms/CustomButton/index.js
  src/components/atoms/Input/InputStyles.js
  src/components/atoms/Input/index.js
  src/components/atoms/checkbox/checkboxStyle.js
  src/components/atoms/checkbox/index.js
  src/components/organism/Formulario/FormStyles.js
  src/components/organism/Formulario/index.js
  src/navigation/MainStack.js
  src/screens/Register.js
  src/screens/styles.js
Labels: code task

#8 Feature# dev
  README.md
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  src/components/atoms/CustomButton/CustomButtonStyles.js
  src/components/atoms/CustomButton/index.js
  src/components/atoms/Input/InputStyles.js
  src/components/atoms/Input/index.js
  src/components/atoms/checkbox/index.js
  src/components/organism/Formulario/index.js
Labels: review required

#12 Feature#10 log in and google auth
  android/app/build.gradle
  android/app/google-services.json
  package-lock.json
  package.json
  src/components/atoms/LoadingIndicator/LoadingStyles.js
  src/components/atoms/LoadingIndicator/index.js
  src/components/organism/Formulario/FormStyles.js
  src/components/organism/Formulario/index.js
  src/library/utils/auth.js
  src/library/utils/authGoogle.js
  src/navigation/MainStack.js
  src/screens/Home.js
  src/screens/Register.js
  src/screens/styles.js
Labels: mentor review required, review required, code task, design task, database

#16 Feature#14 create a form to be able to add flight reservations
  package-lock.json
  package.json
  src/components/atoms/InputSelect/SelectStyles.js
  src/components/atoms/InputSelect/index.js
  src/components/atoms/ListItem/index.js
  src/library/utils/auth.js
  src/navigation/MainStack.js
  src/screens/Date.js
  src/screens/Destination.js
  src/screens/Finish.js
  src/screens/Home.js
  src/screens/Origin.js
  src/screens/Passengers.js
  src/screens/styles.js
Labels: code task, design task

#17 Store flight reservations in firebase
  package-lock.json
  src/components/organism/VerticalList/index.js
  src/library/utils/authGoogle.js
  src/library/utils/database.js
  src/screens/Finish.js
  src/screens/Home.js
  src/screens/Vuelos.json
Labels: database

#20 Filtering the data
  src/library/utils/database.js
Labels: review required
